# Generated by Django 4.2.2 on 2025-06-27 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('github_analyzer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='analysishistory',
            name='chat_history',
            field=models.TextField(blank=True),
        ),
    ]
